[build]
command = "bun install && npm run build:prod"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Explicitly override the install command to NOT use --frozen-lockfile
[build.processing]
skip_processing = false
